"""Facts about a ground-truth dataset, as Markdown, and the human review sheet (ADR-0013, 6).

The summary reports counts and lists only; reading them is left to the people who use them.
The review sheet holds every item a person must check (unconfirmed, flagged as disagreeing or
refuted) and a stratified random sample of the rest, at least one per (task, kind) and
`SAMPLE_SHARE` overall, drawn with a fixed seed.
"""

import csv
import random
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

from trajlab.contracts.groundtruth import GroundTruthItem
from trajlab.groundtruth.counterfactual import read_fixes
from trajlab.groundtruth.extract import TrialInputs, points_path, read_points
from trajlab.groundtruth.gates import trial_gates
from trajlab.groundtruth.items import labels_path, read_items, trial_timeline
from trajlab.groundtruth.minimize import read_reverts
from trajlab.groundtruth.replay import read_records

SAMPLE_SHARE = 0.2
SAMPLE_SEED = "tb40-sonnet-v2-gt-v1"
MUST_REVIEW_FLAGS = ("disagrees_with_regression", "refuted", "not_confirmed")


@dataclass
class TrialFacts:
    inputs: TrialInputs
    reward: float | None
    failing: list[str]
    excluded: list[str]
    items: list[GroundTruthItem]
    labeled: bool
    fixes: int


def collect(inputs: list[TrialInputs]) -> list[TrialFacts]:
    facts = []
    for one in inputs:
        trial_dir = one.trial_dir
        gates = trial_gates(trial_dir)
        excluded = sorted(set(gates.flaky_checks) | set(gates.irreproducible_checks))
        failing = []
        if points_path(trial_dir).is_file():
            failing = [k for k in trial_timeline(trial_dir).final_failing if k not in excluded]
        facts.append(
            TrialFacts(
                one,
                gates.recorded_reward,
                failing,
                excluded,
                read_items(trial_dir),
                labels_path(trial_dir).is_file(),
                len(read_fixes(trial_dir)),
            )
        )
    return facts


def _table(header: list[str], rows: list[list[object]]) -> list[str]:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return out


def markdown(job_dir: Path, inputs: list[TrialInputs]) -> str:
    facts = collect(inputs)
    failed = [f for f in facts if f.reward != 1.0]
    out = [
        f"# Ground truth for `{job_dir.name}`: facts",
        "",
        "Generated by `trajlab gt summary` (ADR-0013). Data: `groundtruth/` inside each trial dir "
        f"of `{job_dir}`.",
        "",
        "## Replays and gates",
        "",
    ]
    outcomes: Counter[str] = Counter()
    purposes: Counter[str] = Counter()
    gate1: Counter[str] = Counter()
    gate2: Counter[str] = Counter()
    points = states = 0
    flaky: list[str] = []
    irreproducible: list[str] = []
    for f in facts:
        trial_dir = f.inputs.trial_dir
        gates = trial_gates(trial_dir)
        gate1[gates.gate1] += 1
        gate2[gates.gate2] += 1
        flaky += [f"{trial_dir.name} {c}" for c in gates.flaky_checks]
        irreproducible += [f"{trial_dir.name} {c}" for c in gates.irreproducible_checks]
        if points_path(trial_dir).is_file():
            found = read_points(trial_dir)
            points += len(found)
            states += len({p.state_id for p in found})
        for record in read_records(trial_dir):
            outcomes[record.outcome] += 1
            purposes[record.purpose] += 1
    out += _table(
        ["Trials", "Failed", "Points", "States", "Replays by purpose", "Replays by outcome"],
        [[len(facts), len(failed), points, states, dict(purposes), dict(outcomes)]],
    )
    out += ["", f"Gate 1: {dict(gate1)}. Gate 2: {dict(gate2)}.", ""]
    out += [f"Flaky checks ({len(flaky)}):", *[f"- {x}" for x in flaky], ""]
    out += [f"Irreproducible checks ({len(irreproducible)}):", *[f"- {x}" for x in irreproducible]]
    out += ["", "## Items", ""]
    items = [i for f in facts for i in f.items]
    kinds = Counter((i.artifact_class, i.kind) for i in items)
    classes = sorted({c for c, _ in kinds})
    kind_names = sorted({k for _, k in kinds})
    out += _table(
        ["Kind", *classes, "All"],
        [
            [k, *[kinds[(c, k)] for c in classes], sum(kinds[(c, k)] for c in classes)]
            for k in kind_names
        ],
    )
    flags = Counter(name for i in items for name in {flag.split(":")[0] for flag in i.flags})
    out += ["", "Flags (items carrying each):", ""]
    out += _table(["Flag", "Items"], [[k, v] for k, v in sorted(flags.items())])
    out += ["", "## Failed trials", ""]
    rows = []
    for f in failed:
        covered = {c for i in f.items for c in i.checks}
        summary = "; ".join(
            f"{i.kind} " + (",".join(f"P{p}" for p in i.points) or "-") for i in f.items
        )
        rows.append(
            [
                f.inputs.trial_dir.name,
                len(f.failing),
                len(f.excluded),
                len(set(f.failing) & covered),
                f.fixes,
                "yes" if f.labeled else "no",
                summary or "-",
            ]
        )
    out += _table(
        [
            "Trial",
            "Failing checks",
            "Excluded",
            "Checks in items",
            "Fixes tried",
            "Labeled",
            "Items (kind, blamed points)",
        ],
        rows,
    )
    out += ["", "## Regressions and their revert tests", ""]
    reg_rows = []
    for f in failed:
        reverts = read_reverts(f.inputs.trial_dir)
        for item in f.items:
            if item.kind == "regression":
                point = int(item.item_id.rsplit("-P", 1)[1])
                revert = reverts.get(point)
                reg_rows.append(
                    [
                        item.item_id,
                        len(item.checks),
                        ", ".join(item.tool_call_ids) or "-",
                        revert.verdict if revert else "untested",
                    ]
                )
    out += _table(["Item", "Checks", "Blamed calls", "Revert"], reg_rows) if reg_rows else ["None."]
    return "\n".join(out) + "\n"


def review_rows(inputs: list[TrialInputs]) -> list[dict[str, str]]:
    """Every item that must be reviewed, and a stratified sample of the others."""
    items = [i for one in inputs for i in read_items(one.trial_dir)]
    must = [i for i in items if i.kind == "unconfirmed" or _flagged(i)]
    rest = [i for i in items if i not in must]
    strata: dict[tuple[str, str], list[GroundTruthItem]] = defaultdict(list)
    for item in rest:
        strata[(item.task_name, item.kind)].append(item)
    rng = random.Random(SAMPLE_SEED)
    sample: list[GroundTruthItem] = []
    for key in sorted(strata):
        sample.append(rng.choice(strata[key]))
    others = [i for i in rest if i not in sample]
    want = max(0, round(SAMPLE_SHARE * len(rest)) - len(sample))
    sample += rng.sample(others, min(want, len(others)))
    rows = []
    for item, reason in [(i, "must") for i in must] + [(i, "sample") for i in sample]:
        rows.append(
            {
                "item_id": item.item_id,
                "reason": reason,
                "task": item.task_name,
                "kind": item.kind,
                "method": item.method,
                "checks": " ".join(item.checks),
                "blamed_calls": " ".join(item.tool_call_ids),
                "step_ids": " ".join(str(s) for s in item.step_ids),
                "lines": "; ".join(
                    f"{h.path}:{','.join(map(str, h.removed)) or f'+{h.inserted_before}'}"
                    for h in item.hunks
                ),
                "fix_id": item.fix_id or "",
                "explanation": item.explanation or "",
                "flags": " ".join(item.flags),
                "reviewer": "",
                "blind": "",
                "decision": "",
                "edits": "",
                "minutes": "",
                "notes": "",
            }
        )
    return rows


def _flagged(item: GroundTruthItem) -> bool:
    return any(flag.startswith(MUST_REVIEW_FLAGS) for flag in item.flags)


def write_review_sheet(path: Path, inputs: list[TrialInputs]) -> int:
    rows = review_rows(inputs)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]) if rows else ["item_id"])
        writer.writeheader()
        writer.writerows(rows)
    return len(rows)
